export const VALIDATED_TOKEN ='VALIDATED_TOKEN';
export const VALIDATION_ERROR ='VALIDATION_ERROR';
export const GET_EVENTS ='GET_EVENTS';
export const EVENTS_LOADING='EVENTS_LOADING'
export const GET_RETKESGECI ='GET_RETKESGECI';
export const SEND_MAIL ='SEND_MAIL';
export const OPEN_ALERT='OPEN_ALERT';
export const CLOSE_ALERT='CLOSE_ALERT';


 